In [ ]:
#NUMPY TUTORIAL

In [2]:
import numpy as np 

In [3]:
tekBoyutluDizi= np.array([1.2,2.3,3.4,4.5,5.6,6.7])
print(tekBoyutluDizi)

[1.2 2.3 3.4 4.5 5.6 6.7]


In [4]:
ikiBoyutluDizi=np.array([[1.2],[1.3],[1.4],[1.5]])
print(ikiBoyutluDizi)

[[1.2]
 [1.3]
 [1.4]
 [1.5]]


In [8]:
dizi=np.arange(5,12) #5 dahil 12 dahil değil arasında sayı dizisi oluştur.
print(dizi)

[ 5  6  7  8  9 10 11]


In [17]:
np.zeros((2,2), dtype=np.int16)

array([[0, 0],
       [0, 0]], dtype=int16)

In [36]:
random_integers_between_50_and_100= np.random.randint(low=50, high=101, size=(6)) #50 ile 100 arasında random 6 tane elemanlı vektör oluştur.
print(random_integers_between_50_and_100)

[86 56 61 64 86 93]


In [28]:
random_floats=np.random.random([3]) # np.random.random 0.0 ve 1.0 arasında random sayı üretir
print(random_floats)

[0.95305558 0.26680847 0.18622096]


In [29]:
random_floats_between_2_and_3 = random_floats + 2.0 #yukarıdaki vektördeki her ögeye 2.0 ekledi böylece değerleriniz 2.0 ve 3.o arasında oldu.
print(random_floats_between_2_and_3)

[2.95305558 2.26680847 2.18622096]


In [38]:
random_integers_between_150_and_300=random_integers_between_50_and_100*3 #yukarıdaki 50 ile 100 arasındaki 6 elemanlı vektörün her bir elemanını 3 ile çarptık.
print(random_integers_between_150_and_300)

[258 168 183 192 258 279]


In [39]:
#TASK1
#1.Feature adlı bir NumPy dizisine 6 ila 20 (dahil) arasındaki tam sayı dizisini atayın.
#2.Label adlı bir NumPy dizisine şu şekilde 15 değer atayın: label = (3)(feature) + 4
feature=np.arange(6,21)
print(feature)
label=(feature*3)+4
print(label)


[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [48]:
#TASK2
#-2 ile +2 arasında farklı bir rastgele kayan nokta değeri ekleyerek label'a atanan her değeri değiştirin.
#label ile aynı boyuta sahip noise dizisi oluşturun.
noise = (np.random.random([15]) * 4) - 2
label = label + noise 
print(label)

[24.46117934 17.06776044 39.05613904 29.73194918 34.91476726 37.0509158
 43.10694731 36.39183113 44.74754475 46.95807619 50.72277496 56.2080516
 57.25692269 58.44039954 66.35265858]


In [52]:
#PANDAS TUTORIAL
import pandas as pd

In [64]:
myData=np.array([[0,3],[2,7],[15,4],[-3,4],[31,8],[10,2],[34,8]]) #7x2'lik bir numpy array
column_names=['temparature','activity'] #sütun isimleri
data_frame=pd.DataFrame(data=myData,columns=column_names) #dataframe oluşturduk
print(data_frame)


   temparature  activity
0            0         3
1            2         7
2           15         4
3           -3         4
4           31         8
5           10         2
6           34         8


In [65]:
print("Rows #0, #1 and #2:")
print(data_frame.head(3),'\n') #ilk 3 dataframe verisini görüntüledik.

Rows #0, #1 and #2:
   temparature  activity
0            0         3
1            2         7
2           15         4 



In [59]:
print("Row #2:")
print(data_frame.iloc[[2]],'\n')#2. indisteki veriler gelir.


Row #2:
   temparature  activity
2           15         4 



In [69]:
print("Rows #1, #2 and #3:")
print(data_frame[2:5],'\n') #birinci indis dahil fakat ikinci indis dahil değil yani 2 ve 4 dahil aradaki de veriler gelecek.

Rows #1, #2 and #3:
   temparature  activity
2           15         4
3           -3         4
4           31         8 



In [71]:
print("Column 'temparature:'")
print(data_frame['temparature'])#sadece temparature sütunu verilerini getirir.

Column 'temparature:'
0     0
1     2
2    15
3    -3
4    31
5    10
6    34
Name: temparature, dtype: int64


In [95]:
#TASK1
#Create an 3x4 (3 rows x 4 columns) pandas DataFrame in which the columns are named 
#Eleanor, Chidi, Tahani, and Jason. Populate each of the 12 cells in the DataFrame with a random integer 
#between 0 and 100, inclusive.
#Output the following:
#the entire DataFrame
#the value in the cell of row #1 of the Eleanor column
#Create a fifth column named Janet, which is populated with the row-by-row sums of Tahani and Jason.
people=['Eleanor','Chidi','Tahani','Jason']
r_int=np.random.randint(low=0,high=101,size=(3,4))
people_df=pd.DataFrame(data=r_int,columns=people)
print(people_df)

print("the value in the cell of row #1 of the Eleanor column: ",people_df['Eleanor'][1])

people_df['Janet']=people_df['Tahani']+people_df['Jason']
print(people_df)


   Eleanor  Chidi  Tahani  Jason
0       82     20      98     54
1       34     71      70      7
2       67     34      77     72
the value in the cell of row #1 of the Eleanor column:  34
   Eleanor  Chidi  Tahani  Jason  Janet
0       82     20      98     54    152
1       34     71      70      7     77
2       67     34      77     72    149


In [114]:
df = pd.DataFrame([[0, 2, 3], [0, 4, 1], [10, 20, 30]],
                  index=[4, 5, 6], columns=['A', 'B', 'C'])
print(df)
reference_to_df=df; 

    A   B   C
4   0   2   3
5   0   4   1
6  10  20  30


In [115]:
df.at[5,'B']=df['B'][5]+8 #at=>Access a single value using a label.
print("Güncellenmis df=%d"%df['B'][5])
print("Güncellenmiş referans df=%d"%reference_to_df['B'][5])

Güncellenmis df=12
Güncellenmiş referans df=12


In [117]:
copy_of_my_df=df.copy()
df.at[4,'A']=df['A'][4]+10
print("Güncellenmis df=%d"%df['A'][4])
print("Güncellenmis copy df=%d"%copy_of_my_df['A'][4])


Güncellenmis df=20
Güncellenmis copy df=10


In [118]:
print(df)

    A   B   C
4  20   2   3
5   0  12   1
6  10  20  30
